import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import vue from "unplugin-vue/esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const production = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "node:*",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
  // Vue SFC support (ADR-0033). The plugin compiles `.vue` single-file
  // components to render functions AT BUILD TIME, so the runtime-only Vue build
  // ships (the default `vue` import resolves to the bundler runtime, which has
  // no template compiler) — no `new Function`/`eval`, which Obsidian's Electron
  // CSP forbids.
  plugins: [vue()],
  // Vue's bundler build references these compile-time feature flags; define them
  // so they fold to constants (and tree-shake the dev-only branches out).
  define: {
    __VUE_OPTIONS_API__: "true",
    __VUE_PROD_DEVTOOLS__: "false",
    __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: "false",
  },
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
