import { type ArtifactKind, classifyArtifactId } from "./artifact-id";

/**
 * Pure breadcrumb projection for the artifact graph (01-§3.3, WS-A4). Every
 * node should render a trail derived from the artifact hierarchy —
 * `Test Hub › Plan › PRD-003 › UC-021` — generated by this `breadcrumbFor`
 * projection rather than the ad-hoc "All Use Cases" link each view grew
 * independently (M4). Kept pure (no I/O): the caller resolves the hierarchy
 * (PRD title, parent-PRD chain) and hands the already-fetched facts in, so the
 * trail is a deterministic function of its inputs and fully unit-testable
 * (ADR-0029: logic in tested modules).
 */

/**
 * One crumb in a breadcrumb trail. `id` is the artifact id (`PRD-003`/`UC-021`/
 * `SM-002`) for the segments that name a node, and `undefined` for the static
 * "home" segments (`Test Hub`, the `Plan` section) — those navigate by their
 * own affordance, not through `openArtifact`. A crumb with an `id` is meant to
 * be a deep-link; a crumb without one is a plain label or a section root.
 */
export interface Crumb {
  /** The visible label (e.g. `PRD-003: Checkout` or `Test Hub`). */
  label: string;
  /** The artifact id this crumb deep-links to, when it names a graph node. */
  id?: string;
  /** The kind of node `id` names, for the caller to route the click. */
  kind?: ArtifactKind;
}

/** The root crumbs every trail starts with — the home node and its planning section. */
const HOME: readonly Crumb[] = [{ label: "Test Hub" }, { label: "Plan" }];

/** A resolved PRD ancestor for the trail: its id and (optional) human title. */
export interface PrdCrumbInput {
  id: string;
  title?: string;
}

/** A resolved Use Case for the trail: its id, title, and (optional) parent PRD chain. */
export interface UseCaseCrumbInput {
  id: string;
  title?: string;
  /**
   * The PRD ancestry, root-first (`[PRD-000, PRD-003]`). Each entry becomes a
   * deep-linkable crumb between `Plan` and the Use Case. Empty when the Use Case
   * has no PRD link yet (`prd-id` is optional until backfilled, ADR-0026).
   */
  prdChain?: readonly PrdCrumbInput[];
}

/** A resolved Story Map for the trail: its id, title, and the product PRD it anchors to. */
export interface StoryMapCrumbInput {
  id: string;
  title?: string;
  /** The product PRD the map anchors to (its `product` field), if resolved. */
  product?: PrdCrumbInput;
}

/** The artifact whose trail to project — a tagged union over the graph node kinds. */
export type BreadcrumbTarget =
  | { kind: "prd"; prd: PrdCrumbInput; ancestors?: readonly PrdCrumbInput[] }
  | { kind: "use-case"; useCase: UseCaseCrumbInput }
  | { kind: "story-map"; storyMap: StoryMapCrumbInput };

/** Labels a node crumb `"<id>: <title>"`, or the bare id when no title is known. */
const nodeCrumb = (node: PrdCrumbInput, kind: ArtifactKind): Crumb => ({
  label: node.title ? `${node.id}: ${node.title}` : node.id,
  id: node.id,
  kind,
});

/**
 * The PRD chain crumbs (root-first) of a Use Case or Story Map target, each a
 * deep-linkable PRD node. Empty when the target has no PRD ancestry resolved.
 */
const prdChainCrumbs = (chain: readonly PrdCrumbInput[] | undefined): Crumb[] =>
  (chain ?? []).map((prd) => nodeCrumb(prd, "prd"));

/**
 * Projects the ordered breadcrumb trail for `target`. The trail is always
 * rooted at `Test Hub › Plan`, then the resolved hierarchy (PRD ancestry),
 * then the target node itself. Pure: a deterministic function of the resolved
 * inputs handed in. The terminal crumb is the target — a caller renders it as
 * the current location (not a link).
 */
export const breadcrumbFor = (target: BreadcrumbTarget): Crumb[] => {
  switch (target.kind) {
    case "prd":
      return [...HOME, ...prdChainCrumbs(target.ancestors), nodeCrumb(target.prd, "prd")];
    case "use-case":
      return [
        ...HOME,
        ...prdChainCrumbs(target.useCase.prdChain),
        nodeCrumb({ id: target.useCase.id, title: target.useCase.title }, "use-case"),
      ];
    case "story-map": {
      const product = target.storyMap.product;
      const productCrumb = product ? [nodeCrumb(product, "prd")] : [];
      return [
        ...HOME,
        ...productCrumb,
        nodeCrumb({ id: target.storyMap.id, title: target.storyMap.title }, "story-map"),
      ];
    }
  }
};

/**
 * Whether `crumb` is a deep-linkable graph node (carries a recognized artifact
 * id) versus a static section/home label. A convenience for thin render code so
 * it doesn't re-derive the classification it already encoded in the projection.
 */
export const isDeepLinkable = (crumb: Crumb): boolean =>
  crumb.id !== undefined && classifyArtifactId(crumb.id) !== null;
