import type { TestHubSettings } from "../../domain/settings/settings";

/**
 * GitHub Actions workflow content (TIS §12.1, US-040, UC-019).
 *
 * The workflow is the proof that the runner is CI-compatible (ADR-0006):
 * `cd .testrunner && npm ci && playwright install --with-deps chromium &&
 * npm run test:ci` must pass on a vanilla Ubuntu image with no Obsidian.
 *
 * The base URL is read at job time from a GitHub Actions repository *variable*
 * (`vars.E2E_BASE_URL`), not baked in at generation time (ADR-0011), and mapped
 * to the `BASE_URL` env var the runner's World already expects (ADR-0013/0014).
 * This keeps the workflow environment-agnostic: switching Environments in the
 * plugin never silently points CI at the wrong URL.
 *
 * Pure: no I/O. The writing/overwrite policy lives in
 * {@link ../services/pipeline-generation-service}.
 */
export const buildGitHubActionsWorkflow = (settings: TestHubSettings): string => {
  // Normalize separators to POSIX: the workflow runs on ubuntu-latest where the
  // repo is checked out with "/" separators, so a Windows-configured
  // `e2e\runner` would otherwise point at a literal backslash path (ADR-0006).
  const runnerPath = settings.paths.testRunnerPath.replace(/\\/g, "/");
  const nodeVersion = settings.ci.nodeVersion.trim() || "22";
  // Honor the configured CI command (settings expose runner.ciRunCommand); a
  // vault whose runner package uses a different script would otherwise get an
  // Actions job that runs the wrong command. Falls back to the default.
  const ciRunCommand = settings.runner.ciRunCommand.trim() || "npm run test:ci";
  // Honor the configured CI install command too (default `npm ci`); a runner
  // that intentionally uses `npm install` or a wrapper would otherwise get an
  // Actions job whose install step doesn't match its lockfile/setup.
  const ciInstallCommand = settings.runner.ciInstallCommand.trim() || "npm ci";

  // Auth credentials are injected from CI secrets so authenticated suites match
  // local execution (runEnv merges active.auth.env, ADR-0014). Emit every
  // auth.env key configured across environments as `${{ secrets.<KEY> }}`.
  const authKeys = [
    ...new Set(
      Object.values(settings.sut.environments).flatMap((e) => Object.keys(e.auth?.env ?? {})),
    ),
  ].sort();
  const authEnvLines =
    authKeys.length > 0
      ? "\n" + authKeys.map((key) => `      ${key}: \${{ secrets.${key} }}`).join("\n")
      : "";

  // US-042: every step runs with cwd = the runner folder, so the same commands
  // a developer runs locally are the ones CI runs — the runner stays standalone
  // (no Obsidian, no plugin) and reachable purely from the git checkout.
  return `# Generated by the Obsidian E2E Test Hub (US-040, UC-019).
# Standalone proof (US-042, ADR-0006): this workflow runs the runner with no
# Obsidian present — \`cd ${runnerPath} && npm ci && npm run test:ci\`.
# BASE_URL is read from a repository variable (ADR-0011); set it under
# Settings → Secrets and variables → Actions → Variables as E2E_BASE_URL.
name: E2E Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${runnerPath}
    env:
      BASE_URL: \${{ vars.E2E_BASE_URL }}${authEnvLines}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${nodeVersion}
          cache: npm
          cache-dependency-path: ${runnerPath}/package-lock.json
      - name: Install dependencies
        run: ${ciInstallCommand}
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run tests
        run: ${ciRunCommand}
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-reports
          path: ${runnerPath}/reports
`;
};
